# -*- mode: ruby -*-
# vi: set ft=ruby :

############################
# Parameters
############################

# The folder path shared with virtual machine e.g. /home/<user>/sharing
SHARING_HOST_FOLDER=ENV['SHARING_HOST_FOLDER']
abort 'Required SHARING_HOST_FOLDER environment variable' if ARGV[0] == 'up' && SHARING_HOST_FOLDER.nil?

############################
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
############################
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder SHARING_HOST_FOLDER, "/host"
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "ubuntu-dev-sandbox"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.box_check_update = false
  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name   = "Ubuntu Dev Sandbox"
    vb.memory = 2048
    vb.cpus   = 2
    vb.customize ["modifyvm", :id, "--ostype", "Ubuntu_64"]
    vb.customize ["modifyvm", :id, "--acpi", "on"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--rtcuseutc", "on"]
    vb.customize ["modifyvm", :id, "--cpuhotplug", "off"]
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "60"]
    vb.customize ["modifyvm", :id, "--pae", "on"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--nestedpaging", "on"]
    vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
    vb.customize ["modifyvm", :id, "--boot1", "disk"]
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.customize ["modifyvm", :id, "--clipboard", "disabled"]
  end

  # create necessary folders
  config.vm.provision "shell", path: "setup.sh"
end